\c VIDIA_database

INSERT INTO products (name, price, description) VALUES 
('GeForce RTX 4090', 1599.00, 'The NVIDIA® GeForce RTX™ 4090 is the ultimate GeForce GPU. It brings an enormous leap in performance, efficiency, and AI-powered graphics. Experience ultra-high performance gaming, incredibly detailed virtual worlds, unprecedented productivity, and new ways to create. It’s powered by the NVIDIA Ada Lovelace architecture and comes with 24 GB of G6X memory to deliver the ultimate experience for gamers and creators.');

INSERT INTO specs (
    product_id, 
    vidia_cuda_cores,
    boost_clock,
    base_clock, 
    standard_memory_config, 
    memory_interface, 
    ray_tracing_cores,
    tensor_cores,
    vidia_architecture,
    vidia_dlss,
    vidia_reflex,
    vidia_broadcast,
    pci_express_gen_4,
    vidia_geforce_experience,
    vidia_ansel,
    vidia_freestyle,
    vidia_shadowplay,
    vidia_highlights,
    vidia_gsync,
    game_ready_drivers,
    vidia_studio_drivers,
    vidia_omniverse,
    birectx_12_ultimate,
    vidia_gpu_boost,
    vlink,
    vulkan,
    vidia_encoder,
    vidia_decoder,
    av1_encode,
    av1_decode,
    cuda_capabilities,
    vr_ready,
    maximum_resolution,
    standard_display_connectors,
    multimonitor,
    hdcp,
    length,
    width,
    slots,
    maximum_gpu_temp,
    idle_power,
    video_playback_power,
    average_gaming_power,
    total_graphics_power,
    required_system_power,
    supplementary_power_connector) VALUES
(
    1,
 16384,
  2.52, 
2.23, 
'24 GB GDDR6X', 
'384-bit', 
'3rd Generation', 
'4th Generation', 
'Ada Lovelace', 
3, 
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'Yes',
'No',
'Yes',
'2x 8th Generation',
'5th Generation',
'Yes',
'Yes',
8.9,
'Yes',
'4K at 240Hz or 8K at 60Hz with DSC, HDR',
'HDMI(2), 3x DisplayPort(3)',
'up to 4(4)',
2.3,
'304 mm',
'137 mm',
'3-Slot (61mm)',
90,
19,
25,
315,
450,
850,
'3x PCIe 8-pin cables (adapter in box) OR
450 W or greater PCIe Gen 5 cable');





